backend:
    name: git-gateway
    branch: main

# this line should not be indented
# publish_mode: editorial_workflow


# these lines must not be indented
media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
        - file: "content/_index.md"
          label: "Home Page"
          name: "home"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Publish Date", name: "date", widget: "datetime"}
            - {label: "Body", name: "body", widget: "markdown"}


